# Change these first
owner: manas9927 # Your GitHub organization or username, where this repository lives
repo: nirnay-status-monitor # The name of this repository

sites:
  - name: Nirnay Application
    url: https://nirnay.io/
  - name: Nirnay APIs
    url: https://nirnay.io/api/v1/


status-website:
  baseUrl: /nirnay-status-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Nirnay** is a suite of tools to simplify hiring for companies without a dedicated hiring team."
  introMessage: This is a status monitor page for application and services running for **Nirnay**
  navbar:
    - title: Status
      href: /
    - title: Nirnay
      href: https://nirnay.io/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
