# Change these first
owner: manas9927 # Your GitHub organization or username, where this repository lives
repo: nirnay-status-monitor # The name of this repository

sites:
  - name: Nirnay Application
    url: https://nirnay.io/
  - name: Nirnay APIs
    url: https://nirnay.io/api/v1/


status-website:
  name: Nirnay Status Monitor
  baseUrl: /nirnay-status-monitor
  logoUrl: https://cdn.nirnay.io/Nirnay_Logo_-_small/b48c868c6f924a82b0a05ca5d262b9c31fa72bc32bf8403dbe7707be343.webp
  introTitle: "**Nirnay** is a suite of tools to simplify hiring for companies without a dedicated hiring team."
  introMessage: This is a status monitor page for application and services running for **Nirnay**
  theme: light
  navbar:
    - title: Nirnay
      href: https://nirnay.io/
    - title: Status Monitor
      href: /

i18n:
  footer: Visit [nirnay.io](https://nirnay.io/) to know more.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
